# Generated by Django 2.1.3 on 2018-12-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillot',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_app.Product'),
        ),
    ]
